# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1umhDY2AMfMcmBrDUTf0S-Cq2ohFiPZmC
"""

pip install opencv-python

from google.colab.patches import cv2_imshow
import cv2
rasm=cv2.imread('AboutElephantsAsian.jpg')
cv2_imshow(rasm)

oqqora=cv2.cvtColor(rasm,cv2.COLOR_BGR2GRAY)
cv2_imshow(oqqora)

ras=cv2.imread('AfricanElephantRangelg.jpg')
cv2_imshow(ras)

oqqora=cv2.cvtColor(ras,cv2.COLOR_BGR2GRAY)
cv2_imshow(oqqora)

ra=cv2.imread('AboutElephants-Forest.jpg')
cv2_imshow(ra)

oqqora=cv2.cvtColor(ra,cv2.COLOR_BGR2GRAY)
cv2_imshow(oqqora)

r=cv2.imread('images.jpg')
cv2_imshow(r)

oqqora=cv2.cvtColor(r,cv2.COLOR_BGR2GRAY)
cv2_imshow(oqqora)

o=cv2.imread('pngtree-lotus-flower-jpg-pink-lotus-flower-image_13023952.jpg')
cv2_imshow(o)

oqqora=cv2.cvtColor(o,cv2.COLOR_BGR2GRAY)
cv2_imshow(oqqora)